const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const $$=(s,c=document)=>[...c.querySelectorAll(s)];

const menu=document.querySelector('.menu-panel');
const menuBtn=document.querySelector('.nav-menu');
const menuClose=document.querySelector('.menu-close');
function setMenu(open){menu?.classList.toggle('open',open);menu?.setAttribute('aria-hidden',String(!open));menuBtn?.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open);if(open)menuClose?.focus({preventScroll:true});}
menuBtn?.addEventListener('click',()=>setMenu(true));menuClose?.addEventListener('click',()=>setMenu(false));$$('.menu-panel a').forEach(a=>a.addEventListener('click',()=>setMenu(false)));

if('IntersectionObserver'in window&&!reduceMotion){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -5%'});$$('.reveal').forEach((el,i)=>{el.style.transitionDelay=`${(i%3)*55}ms`;io.observe(el)})}else $$('.reveal').forEach(x=>x.classList.add('in'));

const nav=document.querySelector('.nav-shell');let lastY=scrollY,navTick=false;addEventListener('scroll',()=>{if(navTick)return;navTick=true;requestAnimationFrame(()=>{const y=scrollY;if(y>240&&y>lastY+5&&!document.body.classList.contains('menu-open'))nav?.classList.add('hidden');if(y<lastY-4||y<100)nav?.classList.remove('hidden');lastY=y;navTick=false})},{passive:true});

const radial=document.querySelector('[data-radial-ring]');const radialList=document.querySelector('[data-radial-list]');
if(radial&&radialList){const originals=[...radialList.children];originals.forEach(x=>radialList.appendChild(x.cloneNode(true)));const items=[...radialList.children];const radiusEm=72;items.forEach((item,i)=>{const deg=(360/items.length)*i-93;item.style.transform=`translate(-50%,-50%) rotate(${deg}deg) translateY(-${radiusEm}em) rotate(${-deg}deg)`});if(!reduceMotion){let angle=0,last=performance.now(),paused=false;const tick=now=>{const dt=Math.min(50,now-last);last=now;if(!paused){angle=(angle+dt*360/90000)%360;radial.style.transform=`rotate(${angle}deg)`}requestAnimationFrame(tick)};new IntersectionObserver(es=>paused=!es[0]?.isIntersecting,{threshold:.01}).observe(radial);requestAnimationFrame(tick)}}

if(!reduceMotion){const title=$$('[data-hero-title] > *');title.forEach((el,i)=>{el.animate([{opacity:0,transform:`translateY(${i===1?'40':'65'}px) rotate(${i===1?'-35':'0'}deg)`},{opacity:1,transform:'none'}],{duration:900+i*80,delay:120+i*70,easing:'cubic-bezier(.625,.05,0,1)',fill:'both'})});document.querySelector('[data-hero-description]')?.animate([{opacity:0,transform:'translateY(22px)'},{opacity:1,transform:'none'}],{duration:850,delay:520,easing:'cubic-bezier(.625,.05,0,1)',fill:'both'})}

const reel=document.querySelector('.fixed-reel');document.querySelector('[data-reel-open]')?.addEventListener('click',()=>{reel?.classList.add('open');reel?.setAttribute('aria-hidden','false');document.body.classList.add('reel-open')});document.querySelector('.reel-close')?.addEventListener('click',closeReel);function closeReel(){reel?.classList.remove('open');reel?.setAttribute('aria-hidden','true');document.body.classList.remove('reel-open')}

const latest=$$('.latest-card'),latestDots=$$('.latest-bullets button');let latestIndex=0,latestTimer;function setLatest(n,user=false){if(!latest.length)return;latestIndex=(n+latest.length)%latest.length;latest.forEach((x,i)=>x.classList.toggle('active',i===latestIndex));latestDots.forEach((x,i)=>x.classList.toggle('active',i===latestIndex));if(user)restartLatest()}function restartLatest(){if(reduceMotion)return;clearInterval(latestTimer);latestTimer=setInterval(()=>setLatest(latestIndex+1),4500)}document.querySelector('[data-vprev]')?.addEventListener('click',()=>setLatest(latestIndex-1,true));document.querySelector('[data-vnext]')?.addEventListener('click',()=>setLatest(latestIndex+1,true));latestDots.forEach((x,i)=>x.addEventListener('click',()=>setLatest(i,true)));setLatest(0);restartLatest();

const aboutBtns=$$('.about-controls button');aboutBtns.forEach((b,i)=>b.addEventListener('click',()=>{aboutBtns.forEach(x=>x.classList.toggle('active',x===b));const portrait=document.querySelector('.about-portrait span');if(portrait)portrait.textContent=i?'AK':'GG'}));

const productCards=$$('.product-card'),productBtns=$$('.product-nav button'),productOrbit=document.querySelector('[data-product-orbit]');let productIndex=0;function layoutProducts(){const step=11;productCards.forEach((card,i)=>{const d=(i-productIndex)*step;card.style.transform=`translateX(-50%) rotate(${d}deg) translateY(${Math.abs(d)*.12}em)`;card.style.zIndex=String(50-Math.abs(i-productIndex));card.classList.toggle('active',i===productIndex)});productBtns.forEach((b,i)=>b.classList.toggle('active',i===productIndex))}productBtns.forEach((b,i)=>b.addEventListener('click',()=>{productIndex=i;layoutProducts()}));layoutProducts();

const quotes=$$('.quote'),quoteDots=$$('.quote-bullets button');let quoteIndex=0,quoteTimer;function setQuote(n,user=false){quoteIndex=(n+quotes.length)%quotes.length;quotes.forEach((x,i)=>x.classList.toggle('active',i===quoteIndex));quoteDots.forEach((x,i)=>x.classList.toggle('active',i===quoteIndex));if(user)restartQuotes()}function restartQuotes(){if(reduceMotion)return;clearInterval(quoteTimer);quoteTimer=setInterval(()=>setQuote(quoteIndex+1),6500)}document.querySelector('[data-qprev]')?.addEventListener('click',()=>setQuote(quoteIndex-1,true));document.querySelector('[data-qnext]')?.addEventListener('click',()=>setQuote(quoteIndex+1,true));quoteDots.forEach((d,i)=>d.addEventListener('click',()=>setQuote(i,true)));if(quotes.length){setQuote(0);restartQuotes()}

const planBtns=$$('[data-plan]');planBtns.forEach(btn=>btn.addEventListener('click',()=>{planBtns.forEach(x=>x.classList.toggle('active',x===btn));$$('.price-number strong').forEach(x=>{const v=btn.dataset.plan==='next'?x.dataset.next:x.dataset.current;if(!reduceMotion)x.animate([{opacity:.15,transform:'translateY(10px)'},{opacity:1,transform:'none'}],{duration:300,easing:'cubic-bezier(.625,.05,0,1)'});x.textContent=v})}));

const flick=document.querySelector('[data-flick]'),flickItems=$$('.flick-item');let flickAngle=0,flickDown=false,flickStart=0,flickBase=0;function layoutFlick(){const n=flickItems.length;flickItems.forEach((item,i)=>{const offset=((i-(n-1)/2)*13)+flickAngle;const y=Math.abs(offset)*.13;item.style.transform=`translate(${offset*1.7}em,${y}em) rotate(${offset*.6}deg)`;item.style.zIndex=String(100-Math.round(Math.abs(offset)))})}layoutFlick();if(flick){flick.addEventListener('pointerdown',e=>{flickDown=true;flickStart=e.clientX;flickBase=flickAngle;flick.setPointerCapture?.(e.pointerId)});flick.addEventListener('pointermove',e=>{if(!flickDown)return;flickAngle=flickBase+(e.clientX-flickStart)*.03;layoutFlick()});const stop=()=>flickDown=false;flick.addEventListener('pointerup',stop);flick.addEventListener('pointercancel',stop)}

const dragCursor=document.querySelector('.drag-cursor');if(dragCursor&&!reduceMotion&&matchMedia('(pointer:fine)').matches){let raf=0,x=0,y=0;addEventListener('pointermove',e=>{x=e.clientX;y=e.clientY;if(!raf)raf=requestAnimationFrame(()=>{dragCursor.style.left=`${x}px`;dragCursor.style.top=`${y}px`;raf=0})},{passive:true});[flick,productOrbit].filter(Boolean).forEach(el=>{el.addEventListener('pointerenter',()=>dragCursor.classList.add('show'));el.addEventListener('pointerleave',()=>dragCursor.classList.remove('show'));el.addEventListener('pointerdown',()=>dragCursor.textContent='HOLD');el.addEventListener('pointerup',()=>dragCursor.textContent='DRAG')})}

const form=document.querySelector('#newsletter-form');form?.addEventListener('submit',e=>{e.preventDefault();const s=form.querySelector('.form-status'),mail=form.querySelector('input[type=email]'),ok=form.querySelector('input[type=checkbox]');if(!mail?.value.trim()){s.textContent='Enter an email address first.';mail?.focus();return}if(ok&&!ok.checked){s.textContent='Please confirm you want project updates.';ok.focus();return}s.textContent="Amazing, we'll keep you in the loop!"});
const year=document.querySelector('#year');if(year)year.textContent=new Date().getFullYear();

document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(reel?.classList.contains('open'))closeReel();else if(menu?.classList.contains('open'))setMenu(false)}});